packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@mongodb-js/zstd': false
  bufferutil: false
  cbor-extract: true
  esbuild: true
  node-liblzma: false
  utf-8-validate: false

minimumReleaseAgeExclude:
  - '@workflow/world-postgres@5.0.0-beta.24'
  - '@ai-sdk/gateway@4.0.11'
  - '@ai-sdk/provider-utils@5.0.5'
  - '@ai-sdk/provider@4.0.2'
  - ai@7.0.14
  - eve@0.23.0

patchedDependencies:
  liveline@0.0.7: patches/liveline@0.0.7.patch
